export {default as DownloadIcon} from "./download.svg"
export {default as GithubIcon} from "./github.svg"
export {default as LinkedInIcon} from "./linkedin.svg"
export {default as TwitterIcon} from "./twitter.svg"
export {default as WebIcon} from "./web.svg"
