import type { Metadata } from 'next';
import { Inter, PT_Sans, Sora } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/navbar';

const inter = Sora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
